name: build
on:
  push:

env:
  ASSETS_URL: "https://api.github.com/repos/melpon/wandbox-builder/releases/32402124/assets"
  UPLOAD_URL: "https://uploads.github.com/repos/melpon/wandbox-builder/releases/32402124/assets{?name,label}"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  gcc:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 10.2.0
          - 9.3.0
          - 8.4.0
          - 7.5.0
          - 6.5.0
          - 5.5.0
          - 4.9.4
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - id: setup
        run: ./ga-build/${{ github.job }}/run.sh setup ${{ matrix.version }}
      - id: install
        if: steps.setup.outputs.need_install == 'true'
        run: ./ga-build/${{ github.job }}/run.sh install ${{ matrix.version }}
      - uses: actions/upload-release-asset@v1
        if: steps.setup.outputs.need_install == 'true'
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ${{ steps.install.outputs.package_path }}
          asset_name: ${{ steps.install.outputs.package_filename }}
          asset_content_type: application/gzip
  clang:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 11.1.0
          - 10.0.1
          - 9.0.1
          - 8.0.1
          - 7.1.0
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - id: setup
        run: ./ga-build/${{ github.job }}/run.sh setup ${{ matrix.version }}
      - id: install
        if: steps.setup.outputs.need_install == 'true'
        run: ./ga-build/${{ github.job }}/run.sh install ${{ matrix.version }}
      - uses: actions/upload-release-asset@v1
        if: steps.setup.outputs.need_install == 'true'
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ${{ steps.install.outputs.package_path }}
          asset_name: ${{ steps.install.outputs.package_filename }}
          asset_content_type: application/gzip
  boost:
    needs: [gcc, clang]
    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.75.0 gcc 10.2.0
          - 1.75.0 gcc 9.3.0
          - 1.75.0 gcc 8.4.0
          - 1.75.0 gcc 7.5.0
          - 1.75.0 gcc 6.5.0
          - 1.75.0 gcc 5.5.0
          - 1.75.0 gcc 4.9.4
          - 1.75.0 clang 11.1.0
          - 1.75.0 clang 10.0.1
          - 1.75.0 clang 9.0.1
          - 1.75.0 clang 8.0.1
          - 1.75.0 clang 7.1.0
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - id: setup
        run: ./ga-build/${{ github.job }}/run.sh setup ${{ matrix.version }}
      - id: install
        if: steps.setup.outputs.need_install == 'true'
        run: ./ga-build/${{ github.job }}/run.sh install ${{ matrix.version }}
      - uses: actions/upload-release-asset@v1
        if: steps.setup.outputs.need_install == 'true'
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ${{ steps.install.outputs.package_path }}
          asset_name: ${{ steps.install.outputs.package_filename }}
          asset_content_type: application/gzip
  clisp:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 2.49
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - id: setup
        run: ./ga-build/${{ github.job }}/run.sh setup ${{ matrix.version }}
      - id: install
        if: steps.setup.outputs.need_install == 'true'
        run: ./ga-build/${{ github.job }}/run.sh install ${{ matrix.version }}
      - uses: actions/upload-release-asset@v1
        if: steps.setup.outputs.need_install == 'true'
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ${{ steps.install.outputs.package_path }}
          asset_name: ${{ steps.install.outputs.package_filename }}
          asset_content_type: application/gzip
