name: gcc
on:
  push:

env:
  ASSETS_URL: "https://api.github.com/repos/melpon/wandbox-builder/releases/32402124/assets"
  UPLOAD_URL: "https://uploads.github.com/repos/melpon/wandbox-builder/releases/32402124/assets{?name,label}"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  gcc:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 9.3.0
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - id: setup
        run: ./ga-build/gcc/run.sh setup ${{ matrix.version }}
      - id: install
        if: steps.setup.outputs.need_install == "true"
        run: ./ga-build/gcc/run.sh install ${{ matrix.version }}
      - uses: actions/upload-release-asset@v1
        if: steps.setup.outputs.need_install == "true"
        with:
          upload_url: "https://uploads.github.com/repos/melpon/wandbox-builder/releases/32402124/assets{?name,label}"
          asset_path: ${{ steps.install.outputs.package_path }}
          asset_name: ${{ steps.install.outputs.package_filename }}
          asset_content_type: application/gzip
