name: heads
on:
  schedule:
    # 毎日 09:00 JST
    - cron: "0 0 * * *"

jobs:
  heads:
    strategy:
      matrix:
        fail-fast: false
        name:
          - gcc-head
          - clang-head
          - swift-head
          - nodejs-head
          - gdc-head
          - openjdk-head
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - run: sudo ./ga-install.sh
        working-directory: build/${{ matrix.name }}
      - run: tar czf ${{ matrix.name }}.tar.gz ${{ matrix.name }}/
        working-directory: /opt/wandbox
      - name: Release ${{ matrix.name }} latest
        uses: WebFreak001/deploy-nightly@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          upload_url: "https://uploads.github.com/repos/melpon/wandbox-builder/releases/22561082/assets{?name,label}"
          release_id: 22561082
          asset_path: /opt/wandbox/${{ matrix.name }}.tar.gz
          asset_name: ${{ matrix.name }}.tar.gz
          asset_content_type: application/gzip
      - name: Release ${{ matrix.name }} nightly
        uses: WebFreak001/deploy-nightly@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          upload_url: "https://uploads.github.com/repos/melpon/wandbox-builder/releases/22561082/assets{?name,label}"
          release_id: 22561082
          asset_path: /opt/wandbox/${{ matrix.name }}.tar.gz
          asset_name: ${{ matrix.name }}-$$.tar.gz
          asset_content_type: application/gzip
          max_releases: 7
